// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9fZGYovxa82EHHxW5RjRH7NwNCUA0zGo',
    appId: '1:760115882423:web:79958603342c2407ab6032',
    messagingSenderId: '760115882423',
    projectId: 'ecomm-app-a42e2',
    authDomain: 'ecomm-app-a42e2.firebaseapp.com',
    storageBucket: 'ecomm-app-a42e2.appspot.com',
    measurementId: 'G-TF5RSYVJVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBWdqTagnPpJbh7ujFHS2NtfXp_VtnII',
    appId: '1:760115882423:android:9c57922972cd1f7eab6032',
    messagingSenderId: '760115882423',
    projectId: 'ecomm-app-a42e2',
    storageBucket: 'ecomm-app-a42e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57YJ3WPu_vPJYXZhK1EPsgv5ZjYvp_-o',
    appId: '1:760115882423:ios:a516be24f8a3943eab6032',
    messagingSenderId: '760115882423',
    projectId: 'ecomm-app-a42e2',
    storageBucket: 'ecomm-app-a42e2.appspot.com',
    iosBundleId: 'com.example.opencartEcommapp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57YJ3WPu_vPJYXZhK1EPsgv5ZjYvp_-o',
    appId: '1:760115882423:ios:da4ece919d17985dab6032',
    messagingSenderId: '760115882423',
    projectId: 'ecomm-app-a42e2',
    storageBucket: 'ecomm-app-a42e2.appspot.com',
    iosBundleId: 'com.example.opencartEcommapp1.RunnerTests',
  );
}
