// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'list_of_product.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Product _$ProductFromJson(Map<String, dynamic> json) => Product(
      success: json['success'] as int?,
      error: json['error'] as List<dynamic>?,
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => products.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$ProductToJson(Product instance) => <String, dynamic>{
      'success': instance.success,
      'error': instance.error,
      'data': instance.data,
    };

products _$productsFromJson(Map<String, dynamic> json) => products(
      id: json['id'],
      product_id: json['product_id'],
      name: json['name'],
      manufacturer: json['manufacturer'],
      sku: json['sku'],
      model: json['model'],
      image: json['image'],
      images: json['images'],
      original_image: json['original_image'],
      original_images: json['original_images'],
      price_excluding_tax: json['price_excluding_tax'],
      price_excluding_tax_formated: json['price_excluding_tax_formated'],
      price: json['price'],
      price_formated: json['price_formated'],
      rating: json['rating'],
      description: json['description'],
      attribute_groups: json['attribute_groups'],
      special: json['special'],
      special_formated: json['special_formated'],
      special_excluding_tax: json['special_excluding_tax'],
      special_excluding_tax_formated: json['special_excluding_tax_formated'],
      special_start_date: json['special_start_date'],
      special_end_date: json['special_end_date'],
      discounts: json['discounts'],
      options: json['options'],
      minimum: json['minimum'],
      meta_title: json['meta_title'],
      meta_description: json['meta_description'],
      meta_keyword: json['meta_keyword'],
      tag: json['tag'],
      upc: json['upc'],
      ean: json['ean'],
      jan: json['jan'],
      isbn: json['isbn'],
      mpn: json['mpn'],
      location: json['location'],
      stock_status: json['stock_status'],
      stock_status_id: json['stock_status_id'],
      manufacturer_id: json['manufacturer_id'],
      tax_class_id: json['tax_class_id'],
      date_available: json['date_available'],
      weight: json['weight'],
      weight_class_id: json['weight_class_id'],
      length: json['length'],
      width: json['width'],
      height: json['height'],
      length_class_id: json['length_class_id'],
      subtract: json['subtract'],
      sort_order: json['sort_order'],
      status: json['status'],
      date_added: json['date_added'],
      date_modified: json['date_modified'],
      viewed: json['viewed'],
      weight_class: json['weight_class'],
      length_class: json['length_class'],
      shipping: json['shipping'],
      reward: json['reward'],
      points: json['points'],
      category: json['category'],
      quantity: json['quantity'],
      reviews: json['reviews'],
      recurrings: json['recurrings'],
    );

Map<String, dynamic> _$productsToJson(products instance) => <String, dynamic>{
      'id': instance.id,
      'product_id': instance.product_id,
      'name': instance.name,
      'manufacturer': instance.manufacturer,
      'sku': instance.sku,
      'model': instance.model,
      'image': instance.image,
      'images': instance.images,
      'original_image': instance.original_image,
      'original_images': instance.original_images,
      'price_excluding_tax': instance.price_excluding_tax,
      'price_excluding_tax_formated': instance.price_excluding_tax_formated,
      'price': instance.price,
      'price_formated': instance.price_formated,
      'rating': instance.rating,
      'description': instance.description,
      'attribute_groups': instance.attribute_groups,
      'special': instance.special,
      'special_formated': instance.special_formated,
      'special_excluding_tax': instance.special_excluding_tax,
      'special_excluding_tax_formated': instance.special_excluding_tax_formated,
      'special_start_date': instance.special_start_date,
      'special_end_date': instance.special_end_date,
      'discounts': instance.discounts,
      'options': instance.options,
      'minimum': instance.minimum,
      'meta_title': instance.meta_title,
      'meta_description': instance.meta_description,
      'meta_keyword': instance.meta_keyword,
      'tag': instance.tag,
      'upc': instance.upc,
      'ean': instance.ean,
      'jan': instance.jan,
      'isbn': instance.isbn,
      'mpn': instance.mpn,
      'location': instance.location,
      'stock_status': instance.stock_status,
      'stock_status_id': instance.stock_status_id,
      'manufacturer_id': instance.manufacturer_id,
      'tax_class_id': instance.tax_class_id,
      'date_available': instance.date_available,
      'weight': instance.weight,
      'weight_class_id': instance.weight_class_id,
      'length': instance.length,
      'width': instance.width,
      'height': instance.height,
      'length_class_id': instance.length_class_id,
      'subtract': instance.subtract,
      'sort_order': instance.sort_order,
      'status': instance.status,
      'date_added': instance.date_added,
      'date_modified': instance.date_modified,
      'viewed': instance.viewed,
      'weight_class': instance.weight_class,
      'length_class': instance.length_class,
      'shipping': instance.shipping,
      'reward': instance.reward,
      'points': instance.points,
      'category': instance.category,
      'quantity': instance.quantity,
      'reviews': instance.reviews,
      'recurrings': instance.recurrings,
    };
